# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins: rubocop-rspec

AllCops:
  SuggestedExtensions: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Style/StringLiterals:
  Include:
    - "spec/**/*"
